### ISSUE TITLE
The new /warp command

### ISSUE THREAD

**Issue by q220** [TheE/MyWarp#133]
I read that /warp search command was changed into /warp list -n <query> but some of my users have issues with the complexity of the command. Would it be possible to add something easier like how /warp search <query> used to be?

I tried adding an alias in commands.yml but it does not seem to when you try to make an alias of two words.

**Comment by TheE** [comment]
No, sorry.

`warp list` and `warp search` always had overlapping functions, but after I added more filtering options to the list command, it could do everything the old search command could do and even more. There is no rational in keeping the search command alive.

Please advise your users to use `warp list -n <query` instead of the old `warp search <query>`. Once they understand how the command works and which filtering options are available, I am sure they are not going to miss the old search command.
