### ISSUE TITLE
Limits of warps.

### ISSUE THREAD

**Issue by MineServidorCraft** [TheE/MyWarp#138]
When i put the limit about warps, plugin tell me that i have reached warps limits.
In the permissionEX i have the permissions that have the page about nodos(permisions).

    - mywarp.cmd.assets.self
    - mywarp.cmd.list
    - mywarp.cmd.give
    - mywarp.cmd.invite
    - mywarp.cmd.uninvite
    - mywarp.cmd.create-private
    - mywarp.cmd.delete
    - mywarp.limit.Obrero

http://pastebin.com/62s3bvWv

In the server said me this:

http://i.imgur.com/tl7HxXX.png

http://i.imgur.com/0eowJMi.png

**Comment by Ironic8b498** [comment]
under the configuredLimits:  get rid of the defaultLimit: lines

**Comment by TheE** [comment]
Correct, the `defaultLimit:` lines need to be removed. [This](http://pastebin.com/EGttcyBX) version should work.

**Comment by MineServidorCraft** [comment]
I was trying with this lines and isn't work. My users gets only 1-2 warps or infinite but not what they are supposed to have.

**Comment by TheE** [comment]
That is likely because limits are overwritten. Limits are assigned in alphabetical order, if a user happens to have the permission for two limits `a` and `b` the alphabetically first (`a`) applies. From your configuration this seems to be the case with the `artesano` limit.

You have two options: Either rename the limits so that the most important is the alphabetically first (e.g. by prefixing the limits with numbers) or negate permissions for other limits within PEX. I would recommend the former.
