### ISSUE TITLE
FlywayException: Found non-empty schema(s)

### ISSUE THREAD

**Issue by kirich1368** [TheE/MyWarp#139]
help please http://pastebin.com/d8A9RXsQ

**Comment by TheE** [comment]
Apparently the MySQL schema you have configured (`eVI_my_base`) contains tables that are not managed by MyWarp, e.g. tables created by yourself manually or by other plugins. Unfortunately you must use a **dedicated schema for MyWarp only** and never manually interfered with this schema, so that MyWarp can properly manage its own tables.

Did this work with an older beta or did you just install MyWarp for this first time?

**Comment by kirich1368** [comment]
My site just takes a lot of plugin data from 1 table.

MyWarp v2.6.5 works fine, but when you add a warp via the sql request, it does not appear in the game(/mywarp list), even after the command /mywarp reload.

	
In the MyWarp v3.0-beta-4, there is no such problem, and after /warp reload, all new warp appear in the /warp list!

**Comment by kirich1368** [comment]
HELP PLEASE
