### ISSUE TITLE
Group Bug or....?

### ISSUE THREAD

**Issue by DutchUser** [TheE/MyWarp#23]
Hi ( PS: sorry for me my bad engels :( )
When i want set group limits is not working.
see here perms list ( PEX )
-----------------------------------
groups:
  Noob:
    options:
      default: true
    permissions:
    - essentials.me
    - mywarp.warp.basic.assets
    - mywarp.limit.Noob
  Noob+:
    inheritance:
    - Noob
    permissions:
    - essentials.afk
    - mywarp.limit.Noob+
  Premium:
    inheritance:
    - Noob+
    permissions:
    - essentials.fly
    - mywarp.limit.Premium
and here the MyWarp limits section.
------------------------------------------
limits:
  enabled: true
  configured-limits:
    default:
      totalLimit: 15
      publicLimit: 1
      privateLimit: 14
    user:
      totalLimit: 30
      publicLimit: 2
      privateLimit: 28
      affectedWorlds:
      - world
    Noob:
      totalLimit: 5
      publicLimit: 0
      privateLimit: 5
    Noob+:
      totalLimit: 10
      PublicLimit: 0
      privateLimit: 10
    Premium:
      totalLimit: 15
      publicLimit: 1
      privateLimit: 14
    Admin:
      totalLimit: 75
      publicLimit: 25
      privateLimit: 50
So is this a bug?

**Comment by TheE** [comment]
I do not think this is a bug, it looks like you did not configure your permissions properly. From what I see, A user in the `Premium` group has permissions for Noop, Noop+ and Premium. MyWarp will use the Noop Limit because it is the alphabetical first of these three (`N` comes before `P` in the alphabet).

So to fix you need to get the limit names in the order you want them to override each other. For example:

| Old name | New Name |
| ------ | ------ |
|Admin | Admin|
|Premium | B_Premium|
|Noob+ | H_Noob+|
|Noob | U_Noob|
