### ISSUE TITLE
warping while on a horse

### ISSUE THREAD

**Issue by Ironic8b498** [TheE/MyWarp#24]
when you warp while on a horse you arrive at destination and it appears the horse is gone, if you log out of minecraft and back in you are on the horse. Also having trouble setting up group limits don't seem to work, most likely something I'm doing wrong.

**Comment by TheE** [comment]
Warping with tamed horses works fine using CraftBukkit 1.7.9-R0.2. What version are you using?

For the group limits: make sure to carefully read the [wiki-page](https://github.com/TheE/MyWarp/wiki/Creation-Limits). The only change with MyWarp3 is the changed definition point for the default limit set but that should be quit obvious. If you still cannot set it up correctly please open a separate ticket and provide MyWarp's configuration file and the permissions-configuration of whatever plugin you are using.

**Comment by Ironic8b498** [comment]
I'm running Spigot 1.8, I noticed that my problem is a little more involved then limits not working,only rank that can create a warp is admins. Did the perms change since all ranks get error saying they don't have permission contact admins.

**Comment by Ironic8b498** [comment]
OK if this will take more then a few days to fix I would like to know if it's possible to go back to the 2.0 version I was running that worked on Spigot 1.8

**Comment by TheE** [comment]
**Warp usage with tamed horses:** Since this works using CraftBukkit 1.7.9-R0.2 it might be a bug with Spigot 1.8. Unless they fix it I would recommend disabling warping with horses in the configuration.

**Permissions:** No, the permissions are the same as before (`mywarp.warp.basic.createprivate`and `mywarp.warp.basic.createpublic, both are included in the `mywarp.warp.basic.*` set). Could you share your permission configuration and MyWarp's configuration file? Without them I can do nothing.

**Downgrade:** Unfortunately not.

**Comment by Ironic8b498** [comment]
http://pastebin.com/76sBgKqM MyWarp config
http://pastebin.com/mzEfP8sx PEX perms

if I made backup of old warp database I should be able to delete folder and start over right?

**Comment by TheE** [comment]
**Warp usage with tamed horses:** Since I cannot reproduce this right now, I pinned this ticket so I can check that again before releasing a Beta version of MyWarp 3.

**Permissions:** I think the limit `0` overrides all other limits. MyWarp evaluates the limits in alphabetical order, stooping with the first limit a user has a permission for. In your case that results in the following order:
1. `0`
2.  `1`
3.  `2`
4. `Guard`
5.  `VIP`

If, for example, a user in the group `Guard` is checked he has permissions for all of these limits due to inheritance. When evaluating the limits, MyWarp sees he has the limit `0` and does not check the others. The solution is to rename the limits so that their alphabetical order represents their logic order:

| New name | Old name |
| ----- | ----- |
| 0 | v_0 |
| 1 | q_1 |
| 2 | l_2 |
| VIP | g_vip |
| Guard| b_guard |

**Downgrade:** If you have a backup of your old (MyWarp 2.x) database you can of course downgrade. You just need to regenerate your configuration.

**Comment by Ironic8b498** [comment]
I changed my group names within MyWarp config to z0, y1, x2 and now it sees the default limits work for all groups but not the set group limits I set in config.

**Comment by TheE** [comment]
Have you edited the permissions accordingly? The default limit is only used when none of the specific limits applies.

**Comment by Ironic8b498** [comment]
The perms I'm using is     - mywarp.limit.z0 and the group is 0

**Comment by TheE** [comment]
If it is still relevant, try removing the `[]` after the `configuredLimits:` entry. They declare an empty group so it is possible that the configuration parser therefore ignores all configured limits and uses the default one for everybody.

**Comment by Ironic8b498** [comment]
When I delete the [] after configuredLimits: and reload the plugin it is been replaced so I can't get rid of the []. I try moving configuredLimits: [] after my group limits and it puts back in front, like some little gremlin don't want me to figure this out.

**Comment by TheE** [comment]
First download the latest devBuild. There was indeed a small but fatal error with the permission check that has been fixed.

Next your custom limits need to be indented under the `configuredLimits` so that the YAML processor recognises them as group. For example:
````YAML
limits:
  enabled: true
  defaultLimit:
    totalLimit: 1
    publicLimit: 0
    privateLimit: 1
  configuredLimits:
    z0:
      totalLimit: 1
      publicLimit: 0
      privateLimit: 1
    y1:
      totalLimit: 1
      publicLimit: 0
      privateLimit: 1
    x2:
      totalLimit: 4
      publicLimit: 1
      privateLimit: 3
    VIP:
      totalLimit: 30
      publicLimit: 5
      privateLimit: 25
    Guard:
      totalLimit: 50
      publicLimit: 10
      privateLimit: 40
```

**Comment by Ironic8b498** [comment]
I was able to set the limits now, was starting to think it was me not understanding how to do this. Warping with a horse is still a 30% chance of needing to log off server then return if the horse is not seen when you warp, once when I logged in the horse was still not there. Is there a setting I can change to help to make warping with a horse more stable?  I'm still very happy with the way the plugin works!!!
