### ISSUE TITLE
MyWarp Command not working?

### ISSUE THREAD

**Issue by DutchUser** [TheE/MyWarp#26]
Hey, i have trouble with /warp <name> because i have essentials and there is also a /warp <name> option do you now how i fix this?
When hes trying it there stand: No such warp '<name>'

**Comment by TheE** [comment]
First, MyWarp also comes with the `mywarp` and `mw` aliases that can be used instead of MyWarp's `warp`.

Second: I think you can disable commands right in Essentials. There should be an entry named `disabled commands` some where in the Essentials configuration where you can add the warp entry. If this does not work I suggest to ask in the Essentials IRC as they can help you much better than I can (long time CommandBook user).
