### ISSUE TITLE
Warp limits aren't working

### ISSUE THREAD

**Issue by wesley27** [TheE/MyWarp#34]
Hello, my warp limits which have been set for years aren't working. Did the permissions change for limits in MyWarp 3.0?

Here's my config: http://pastebin.com/S12VKcYJ

And we're using "mywarp.limit.gray" for example, as the permission.

Thanks!

**Comment by TheE** [comment]
Not the definition, but configuration. Custom limits are now stored under `configuredLimits` rather than under `configured-limits`.

[This](http://pastebin.com/Lxep2qZp) config should work - I removed everything that is not needed by MyWarp3 (plus the `limit` that was added by MyWarp 2 automatically). Please note that it is recommended to start with a fresh configuration when updating to MyWarp3.
