### ISSUE TITLE
Use of /warp import pre3-mysql is not working.

### ISSUE THREAD

**Issue by veteranmina** [TheE/MyWarp#36]
When attempting to import the old mysql database, which the schema was renamed to mywarpold, it states it cannot connect to the database. At first I thought I had a typo and re-checked it a few times, all good. So tried again and it still fails.

Looking at logs, this is all it gives me to deal with:

````
CONSOLE: [INFO] Import started. This may take some time...
7:47:36 PM CONSOLE: [INFO] Could not establish database connection in order to import warps: Failed to connect to the database.
````

This is the exact command that I am typing (minus user/pass)

    /warp import pre3-mysql jdbc:mysql://localhost/mywarpold user pass warpTable

I have tried multiple times to get this to work, but it does not want to import itself to the new database.

**Comment by TheE** [comment]
Are you sure that the DSN is correct? Perhaps your MySQL server listens to a non standard port that needs to be given too?

Perhaps I should add some more debug output, the current error is not really specific.

**Comment by veteranmina** [comment]
It is the correct DSN, as it connects to the new database using the exact same DSN in the configuration. The port is also using the standard 3306 port. This is why I was stumped when it kept giving me this error.

**Comment by TheE** [comment]
I just tested it with my setup and it works as expected. Are you perhaps using an older devBuild? There was a similar bug, but that has been fixed.

**Comment by veteranmina** [comment]
I was using build #33 to upgrade. I can attempt to use a newer version to see if that works. The reason I had used that version was due to build#34 had the potential break.

**Comment by TheE** [comment]
No, it should work fine with build#33, I just tested it. (Updating is still encouraged.)

 Another guess: You mentioned that you renamed the scheme. Have you checked if the user, you are using to connect with the database, has the rights to access that scheme and use `SELECT`?

**Comment by veteranmina** [comment]
I had used root to create and then access the database, I can double check once I get off work to see. 

Could possibly dropping the db and restoring under a different name have anything to do with it?

**Comment by TheE** [comment]
I doubt it because even if, it should not matter for `root`.

I just pushed a new devBuild that should actually show the SQL error that happened. If you test it, please post the exact output of using the command you posted above, it might give us an idea about the cause.

**Comment by veteranmina** [comment]
Looking at permissions, both root and my main admin user have full perms per the picture here.
![screen shot 2015-03-13 at 10 57 12 am](https://cloud.githubusercontent.com/assets/1810464/6642056/df2afe8c-c96f-11e4-8efd-69bff94e6c3a.png)

**Comment by TheE** [comment]
I just got a mail with the comment you removed (the MySQL Workbench image). The thing I noticed, there is no schema named `mywarpold`, there is only `warp` and `mywarp` and I assume that the later on is the new one.

Is this intentional, have you tested `/warp import pre3-mysql jdbc:mysql://localhost/warp user pass warpTable`?

**Comment by veteranmina** [comment]
Sorry about that, I removed it after i noticed you had just posted the new devBuild. The one called warp is the old one, i had changed the name and had also tried with it as well. I am currently getting the new dev build on the server.

**Comment by veteranmina** [comment]
Quite interesting, i uploaded the new build40 and ran this command:

/warp import pre3-mysql jdbc:mysql://localhost/warp user pass warpTable

It worked perfectly importing all warps.

**Comment by TheE** [comment]
Strange, maybe you were (without knowing) running a build older than 52cc629591133a2fb5425b6de79d6810916706fb (build17).

Anyway, I am glad that it is working now.

**Comment by veteranmina** [comment]
Could have thought i had the right one, but in the end thank you very much for the support!

**Comment by TheE** [comment]
And, to answer the last question: Warps are skipped for four reasons:

1. Important data is missing, for example location or name. There is absolutely nothing that can be done in that case.
2. The warp cannot be connected with a loaded world, which means there is no world with a name as stored in the old database. This can be fixed by renaming an existing or creating a new world with such a name.
3. No unique ID can be found for the player who created the warp. The names are resolved directly from Mojang's servers when importing. If these do not know a player, he might either have changed his name (?) or has no paid account. In both cases, there is nothing that could be done.
4. The warp is _exported_ successfully, but a warp with that name already exists which is why it cannot be imported. Simply remove or rename the existing warp and it should work fine.

In every case, you should see precise information about what is going on logged to the console.

**Comment by veteranmina** [comment]
Alright makes sense, again thank you very mush for the support. It's nice to see developers like yourself this helpful!
