### ISSUE TITLE
Inproper warp counts

### ISSUE THREAD

**Issue by NJ2013** [TheE/MyWarp#37]
My players have reported warps not counting as specified they are allowed 20 and the plugin is saying they are maxed out at 4. The other players are not having an issue just the rank "Legend", no errors and i have had multiple people look at it and not see a reason for it to be malfunctioning.
~NJ

**Comment by TheE** [comment]
What version of MyWarp are you using? Could you post (e.g. via [hastbin](http://hastebin.com/)) your configuration file and the relevant parts of your permission configuration?

**Comment by NJ2013** [comment]
http://hastebin.com/arukavawih.sm
I havent use hastebin so I can only hope that works
I am still looking for the version

**Comment by NJ2013** [comment]
http://hastebin.com/ijemahudof.sm
That is the permissions file, to my knowledge all previous ranks function as they are supposed to

**Comment by TheE** [comment]
First you **must never** post your MySQL information somewhere. I removed them from the configuration file you posted above, but I still recommend to change your MySQL password to be sure that nobody has access to your MySQL server.

What are the permissions of the `member` group? If they have the `mywarp.limit.Member` permission, this might cause the issue. Limit permissions are resolved in [lexicographical order](http://en.m.wikipedia.org/wiki/Lexicographical_order). Since `mywarp.limit.Member` comes before `mywarp.limit.more` it applies instead of the desired `more` limit. 

If I am correct, you should be able to fix it by simply negating the `mywarp.limit.Member` permission for the `Legend` group.

**Comment by NJ2013** [comment]
Ok thank you, I did not see them there when I copied it.
So to double check my understanding, the limit group each rank needs is only the limit they are using?
Thank you again i will try this today

**Comment by NJ2013** [comment]
One of the affected players is saying it is working further than it did but i want to check with a few others before I call it fixed, Thank you for your time I will reply again soon

**Comment by TheE** [comment]
>So to double check my understanding, the limit group each rank needs is only the limit they are using?

Limit permissions are resolved in [lexicographical order](http://en.m.wikipedia.org/wiki/Lexicographical_order), so e.g. if someone happens to have the permissions for the limit `awesome` and `boring`, the first applies.

You can either name your limits with this in mind - so that, if a user has multiple limits due to inheritance, the most important one applies - or you can explicitly negate the permissions for all unwanted limits as you do now. Both solutions work, but it depends on your setup with way is the better.
