### ISSUE TITLE
Config file

### ISSUE THREAD

**Issue by Ironic8b498** [TheE/MyWarp#40]
I did a quick search on mywarp.limit.disobey.[WORLDNAME].total and couldn't find anything on how to set up config to change limits per groups and worlds.

**Comment by TheE** [comment]
For some reason, GitHub's search does not seem to search the wiki so it is pretty much useless. Creation limits are explained [here](https://github.com/TheE/MyWarp/wiki/Creation-Limits), including configuration examples for Bukkit and all disobey permissions.

Please let me know if anything is unclear after reading the article or if you have additional questions so I can improve it.

**Comment by Ironic8b498** [comment]
Ok got the config figured out, had a little issue with typo's but I got it under control now. I think you should add how to add a rank the is a number, I have three groups 0, 1, 2 and not all server owners may know they need to add ' to allow the script to run. just a little fuzzy on the mywarp.limit.disobey which means to over ride set limits default or group limits?

**Comment by TheE** [comment]
The disobey permissions disobey _every_ limit, regardless if configured or default. For users with such a permission, the corresponding limit is never checked, e.g. for the `mywarp.limit.disobey.test-world.total` permission, the total warp limit on the world `test-world` is never checked.

To overwrite a configured limit with another one, you must make use of the [lexicographical resolution](http://en.m.wikipedia.org/wiki/Lexicographical_order). Judging from your permissions configuration, `0`, `1`, `2`, `vip` and `xrayer` will all have the `recruit` limit due to permission inheritance. To solve it, you could rename your limits like this:

| Old name | New Name |
| ------ | ------ |
| recruit | z_recruit |
| xxx | r_0 |
| griefer | p_griefer |
| xrayer | p_xrayer<br/>You could also simply use the `p_griefer` limit. |
| yyy | o_1 |
| zzz | k_2 |
| vip | g_vip |
| guard | d_guard |
| admin | a_admin |

**Comment by Ironic8b498** [comment]
Thanks got it now, on older version of plugin I had the zzz at top that's why it worked then. I used the new names you suggested and got rid of griefer and xrayer and used z_recruit since I was using the same settings for those three.

**Comment by TheE** [comment]
Glad you got it working. :)

**Comment by Ironic8b498** [comment]
I knew it was me just didn't know what I was doing wrong, Thanks for finding my error.
