### ISSUE TITLE
Limitations for private warps using nodes

### ISSUE THREAD

**Issue by TWSSYesterday** [TheE/MyWarp#52]
Perhaps have limitations via permission nodes? I know PlotMe has a system like this, although with MyWarp it would remove the use of the groups having a set number, but being attributed a permission such as mywarp.limit.5

**Comment by TheE** [comment]
I would prefer such a system, but that is not possible using Bukkit's permission API only. You need to directly reference a permissions plugin that supports such a system (only a minority does). Vault can help to some extend, but the system will still not work if the permission plugin itself does not support the feature. Besides I see no way to realize the current multi-world configuration using nodes only.

That said, if _other_ implementations actually allow such value-notes, MyWarp's core is written in a way that these value-nodes can be used instead of groups.
