### ISSUE TITLE
RE: Bug?

### ISSUE THREAD

**Issue by DutchUser** [TheE/MyWarp#56]
Hello. In previous ticket...

Anyway. I dont understand how i must import them. How must i do that command if i want stay using SQLIte? (ans still have the warps)

I dont understand the way how the command work (what i must remove or change)

Greetz, KingVocalWolf

**Comment by TheE** [comment]
Unfortunately you cannot use SQLite on Bukkit because the SQLite version bundled by Bukkit is to old to be usable. Updating it is technically impossible (blame the CraftBukkit developers).

You should use H2 instead, like SQLite the database its stored in a file on the hard drive. To do so, simply start the MyWarp3-beta2 and use the following command:

    /mw import current jdbc:sqlite:/path/to/sqlite/db

Replace '/path/to/sqlite/db' with the full path to MyWarp's old SQLite database (the file called 'mywarp.db' in MyWarp's plugin folder), for example:

    /mw import current jdbc:sqlite:C:/minecraft-server/plugins/MyWarp/mywarp.db

**Comment by DutchUser** [comment]
When i try that 
/mw import current jdbc:sqlite:C:/minecraft-server/plugins/MyWarp/mywarp.db and 
/mw import current jdbc:sqlite:plugins/MyWarp/mywarp.db)

Both give an error and do nothing.
http://nl.tinypic.com/?t=postupload

**Comment by TheE** [comment]
Strange, could you send me your `mywarp.db` file?

**Comment by DutchUser** [comment]
How?

**Comment by DutchUser** [comment]
https://www.dropbox.com/s/qn3it2q16j9st1d/mywarp.db?dl=0

**Comment by TheE** [comment]
It seems like your database is messed up, most warps do not have a valid creation date. This causes the error you reported above.

I fixed it by replacing the invalid creation date with the oldest one I could find in the database, the date of the warp `spawn`. Please download the fixed database [here](https://dl.dropboxusercontent.com/u/13777859/mywarp.db) and _replace_ your existing `mywarp.db`with it. Then run:

    /mw import current jdbc:sqlite:plugins/MyWarp/mywarp.db

**Comment by DutchUser** [comment]
Thx its work now :)
