### ISSUE TITLE
"No players matched query" when attempting to create a warp

### ISSUE THREAD

**Issue by editgal** [TheE/MyWarp#57]
I have edited the config file to represent the number of warps I want. I do not have MySQL enabled (not entirely sure how to use MySQL, plus earlier versions of MyWarp worked just fine without it). When I do the command /help mywarp, I get a "list" of commands with mywarp and it just includes "/mywarp:warp". I even get this when I am an OP.

Attached is a picture of the two commands I performed. 
First, /warp set asdfghjkl and /warp create asdfghjkl. I got "No players matched query."

There are no other warp plugins installed (besides CommandBook, but those warp permissions aren't given).

![mywarp](https://cloud.githubusercontent.com/assets/13322873/8662572/35b572ee-298f-11e5-82b4-0d5d10a561d4.png)

**Comment by TheE** [comment]
I am not entirely sure, but `/warp` _might_ actually call CommandBook's warp functions, as I believe CommandBook has a function to teleport other players to warps using such a syntax. Could you please try if using `mywarp` instead of `warp` results in the same error (e.g. `/mywarp set asdfghjk`)?

That said, to call MyWarp's real help, use `/mywarp help` (or `/warp help` if the problem above is resolved). Sadly Bukkit's help (`/help` is not really usable for sub-commands).

**Comment by editgal** [comment]
/mywarp set asdfghjkl works as an OP rank, but not as a default rank. "You do not have permission to use this command" is the response I get. 

I have these permissions set up in PermissionsEx:
![mywarp](https://cloud.githubusercontent.com/assets/13322873/8662739/eb0b9474-2990-11e5-9410-8df3a9598233.png)

**Comment by TheE** [comment]
What version of MyWarp are you using? The permissions above should be correct, but only for MyWarp3.

**Comment by editgal** [comment]
Aaaand there was the problem. I inadvertently downloaded MyWarp v2.6.5 by simply using the "Download" button. Everything works accordingly using the command /mywarp followed by set, remove, etc.

Thanks for the help!
