### ISSUE TITLE
Group thingie

### ISSUE THREAD

**Issue by DutchUser** [TheE/MyWarp#62]
Hello. The group limits are not working :(
I use mywarps last version 

MyWarp config,
http://pastebin.com/5CDtfuud

Pex perms
- mywarp.limit.vip
- mywarp.limit.master

* Edit,  God is working

**Comment by DutchUser** [comment]
Oke wtf. When i try testing myzelf it is just working. Please don't close it. Ik wil close it if it is not going glitch again in 3 days.

**Comment by DutchUser** [comment]
Hello. The issue about limts is fixed and is not coming back. But when i today look in de warp list i see some warps that owned/created by an UUID and not an player name. How can happand this?
<a href="http://nl.tinypic.com?ref=30x7atw" target="_blank"><img src="http://i59.tinypic.com/30x7atw.png" border="0" alt="Image and video hosting by TinyPic"></a>

**Comment by TheE** [comment]
Generally this can happen if MyWarp does not know the name of the user who created the warp. Still normally this should not happen unless warps where imported and the `profiles.db `was removed or altered afterwards. However, once the player with that UUID logs in, his name should be displayed instead of the UUID.

I do not think that the warp is on a removed world - if it where, it would not be displayed. You can find out more using the info command like so: `/warp info e960`.

**Comment by DutchUser** [comment]
Error on startup:
INFO:
Server version 1.8.7

http://pastebin.com/qMnQAwF0

**Comment by DutchUser** [comment]
Hello. I still not understand the permission limits thing. Can you help with it?
--------------------------------------------
MW limit name ExVip
Permission mywarp.limit.ExVip
--------------------------------------------
MW limit name ExMaster
Permission mywarp.limit.ExMaster
--------------------------------------------
MW limit: ExGod
Permission: mywarp.limit.ExGod
---------------------------------------------
MW limit: Vip
Permsission: mywarp.limit.Vip
---------------------------------------------
MW limit: Premium
Permsission: mywarp.limit.Premium
---------------------------------------------
MW limit: Master
Permsission: mywearp.limit.Master
---------------------------------------------
MW limit: God
Permsission: mywarp.limit.God
---------------------------------------------
MW limit: Legend
Permsission: mywarp.limit.Legend

**Comment by TheE** [comment]
The permissions for each limit are correct. But please keep in mind that, if a user happens to have the permissions for more than one limit (witch can happen due to inheritance), the _alphabetical first_ applies.

For example, if I have the following permissions:

    mywarp.limit.ExGod
    mywarp.limit.God

The limit `ExGod` would apply because in the alphabet, `E` comes before `G`.

**Comment by DutchUser** [comment]
Thx the limits working etc, etc, to make it short i not have any issue. So i close this ticket
