### ISSUE TITLE
Slow Response Lag!

### ISSUE THREAD

**Issue by AdminZero** [TheE/MyWarp#68]
This seems to be taking longer then it should to complete:  
````
MyWarp v3.0-beta-3+jenkins-b98.git-623f42cTotal: 7.131 s	Pct: 0.03%
   Pct Total	Pct Tick	   Total	      Avg	 PerTick	     Count		Event
       0.03%	 184.61%	  7.11 s	    92.30 ms	 0.0	       0.1k	    SquirrelIdProfileService::onPlayerLogin(PlayerLoginEvent)
````

Any thing i can change in the config to fix this or whats the problem?  

Thanks

**Comment by TheE** [comment]
First of, timings are neither accurate nor helpful in diagnosing a problem because they simply track how much time a plugin needs to parse a certain event. The do not track what exactly happens, e.g. if another plugin interferes with the parsing of the tested plugin. In contrast, what is really helpful are CPU samplers(witch you can quit easily generate with [WarmRoast](https://github.com/sk89q/warmroast)).

That said, what happens in the measured event is that MyWarp takes the UUID and the name of player who loggs in and stores it in its SQLite cache. This is a necessary step to continue to use player names when working with warps.
Generally such a cache should be provided by Bukkit, but since Bukkit is dead this is the only working method I am aware of (other mods such as Sponge will provide such a cache and the problem will not exist there). So unless there is a specific problem within the implementation of the cache functionality that can be diagnosed with CPU sampling, I fear that there is nothing I can do for now. :/

**Comment by AdminZero** [comment]
thanks for the reply.  i understand timmings dont provide much imformation,
but its clear something with the mywarps not liking something.  i would be
happy ro provide you with my warmroats link and some screenshots of it and
full server logs or anything you require.  im using spigot 1.8.3 and java
8. thanks.

**Comment by TheE** [comment]
If you are able to run WarmRoast for a couple of hours (ideally when lots of logins happen), this might help me a lot in understanding what's going on. I need either a screenshot of the whole tree of MyWarp (it should say `SquirrelIdProfileService` somewhere), or the link to the running WarmRoast instance (it is probably the best if you send this link to thee@online.de instead of posting it publicly here).
