### ISSUE TITLE
Tab complete for Warps, Players and Profiles

### ISSUE THREAD

**Issue by TheE** [TheE/MyWarp#83]
With the update to Intake 4 Tab complete is finally technically supported. Currently none of the custom Providers implements it, though.

This should be changed:
* `Warp`s can use the MatchList (and warp popularity) directly
* `LocalPlayer`s should behave as in vanilla Minecraft
* `Profile`s cannot be properly parsed without a decent ProfileCache (not really available in Bukkit), so perhaps they can hook into the Player parser.

**Comment by TheE** [comment]
As of writing, Intake does not yet appear to implement per-argment completion (although the foundation is already there in Provider`).

**Comment by kosakriszi** [comment]
I understand this is a long term goal, however I had a question about it. Are you planning on merging kashike's tab complete implementation from his fork of Intake, or are you planning on creating your own? The reason I ask is because I use your fork of Intake for the internationalization features, but would appreciate the ability to finish tab completion for my plugin.

**Comment by TheE** [comment]
I will probably use kashike's implementation (I was not aware of it until now).

That said, I recommend to not rely on my own fork (specifically the hosted version in my maven repo) entirely: There is currently no automatic upload of build artifacts and I cannot guarantee that there are no breaks between SNAPSHOT versions.

**Comment by kosakriszi** [comment]
Okay, that sounds good, and thank you for the heads up!

**Comment by TheE** [comment]
FYI, successful builds from my Intake fork are now automatically uploaded to my SNAPSHOT maven repository at cloudbees.

Support for tab competition will be implemented as soon as I have time (hopefully before the end of this month).
