### ISSUE TITLE
Warps unavailable after any sub-world removal

### ISSUE THREAD

**Issue by Ghostlyr** [TheE/MyWarp#93]
After any sub-world removal creating new warps and warp listing makes unavailable - mywarp provides "world 'worldid' is not present on the server" error. Use of old warps is possible but new created warps are removes after some time. Even after removal of all previously created warps issue still exists.

No errors on server log.
Using last MyWarp dev-build.
Server version: 1.7.10 (Thermos b54 https://github.com/TCPR/Thermos/releases)

**Comment by TheE** [comment]
This is somewhat intentional, although I admit the solution is not ideal.

The problem is that there is way to properly track if a world is deleted when the server is not running; additionally existing worlds can be unloaded and non-existing worlds can be loaded at any time _while_ the server is running. Therefore MyWarp currently simply fails if the warp's world is not available but remain loaded.

This not only renders the warp in question unusable, but also affects whole commands like `warp list` or `warp create` (because limits check each warp's world).

I guess I could try to implement a per-world loading that dynamically unloads warps if their world is unloaded and reloads them if their world is loaded.

This is however a quit major change, do not expect anything until in mid-May (to much stress witch other stuff at the moment).

**Comment by Ghostlyr** [comment]
Okay. I'll wait for fix.
I use default h2, but I did not find any software to conveniently edit it. Can you give advice how i can migrate to MYSQL DB? I tried to use import command, but it shows this message and does not happens nothing:

`[Server] INFO Import started. This may take some time...`
`[Server] INFO Could not establish database connection in order to import warps: SQL [select "mywarp"."warp"."name", "c"."uuid", "mywarp"."warp"."type", "mywarp"."warp"."x", "mywarp"."warp"."y", "mywarp"."warp"."z", "mywarp"."warp"."yaw", "mywarp"."warp"."pitch", "mywarp"."world"."uuid", "mywarp"."warp"."creation_date", "mywarp"."warp"."visits", "mywarp"."warp"."welcome_message", "mywarp"."player"."uuid", "mywarp"."group"."name" from "mywarp"."warp" join "mywarp"."world" on "mywarp"."warp"."world_id" = "mywarp"."world"."world_id" join "mywarp"."player" "c" on "mywarp"."warp"."player_id" = "c"."player_id" left outer join "mywarp"."warp_player_map" on "mywarp"."warp_player_map"."warp_id" = "mywarp"."warp"."warp_id" left outer join "mywarp"."player" on "mywarp"."warp_player_map"."player_id" = "mywarp"."player"."player_id" left outer join "mywarp"."warp_group_map" on "mywarp"."warp_group_map"."warp_id" = "mywarp"."warp"."warp_id" left outer join "mywarp"."group" on "mywarp"."warp_group_map"."group_id" = "mywarp"."group"."group_id"]; (Message 90079 not found); SQL statement:`
`[Server] INFO select "mywarp"."warp"."name", "c"."uuid", "mywarp"."warp"."type", "mywarp"."warp"."x", "mywarp"."warp"."y", "mywarp"."warp"."z", "mywarp"."warp"."yaw", "mywarp"."warp"."pitch", "mywarp"."world"."uuid", "mywarp"."warp"."creation_date", "mywarp"."warp"."visits", "mywarp"."warp"."welcome_message", "mywarp"."player"."uuid", "mywarp"."group"."name" from "mywarp"."warp" join "mywarp"."world" on "mywarp"."warp"."world_id" = "mywarp"."world"."world_id" join "mywarp"."player" "c" on "mywarp"."warp"."player_id" = "c"."player_id" left outer join "mywarp"."warp_player_map" on "mywarp"."warp_player_map"."warp_id" = "mywarp"."warp"."warp_id" left outer join "mywarp"."player" on "mywarp"."warp_player_map"."player_id" = "mywarp"."player"."player_id" left outer join "mywarp"."warp_group_map" on "mywarp"."warp_group_map"."warp_id" = "mywarp"."warp"."warp_id" left outer join "mywarp"."group" on "mywarp"."warp_group_map"."group_id" = "mywarp"."group"."group_id" [90079-176]`

**Comment by TheE** [comment]
For future reference: H2 contains a pretty nice GUI editor that can be used to edit any H2 database.

* http://www.h2database.com/html/quickstart.html#h2_console
* http://stackoverflow.com/a/2897207

**Comment by Ghostlyr** [comment]
Any news? It appears highly problematic to remove world warps after each its "regeneration" :(
