### ISSUE TITLE
request: Add option to use color codes in the message's 

### ISSUE THREAD

**Issue by DutchUser** [TheE/MyWarp#97]
Can you add support for color codes in the message's? Like &6 &4 etc,

**Comment by TheE** [comment]
In version 2 the translation files (partly) supported color codes; I removed them because the files were quit messy and the codes did not exactly behave as you would expect (additional resets were often ended were you would not expect them).

Because users can contribute translations it is more important that these translations can be created easily; additionally the system I am currently using makes it relatively easy to unify formatting of all messages.

Therefore I will not allow color codes within translations, sorry.
